filebeat.inputs:
  - type: log
    id: springboot-fraud-logs
    enabled: true
    paths:
      - /var/log/apps/fraud-service/application.log
      - /var/log/apps/fraud-service/application.*.log
    json:
      keys_under_root: true
      overwrite_keys: true
      add_error_key: true
      message_key: message
    fields:
      service: fraud-service
    fields_under_root: false

  - type: log
    id: laravel-account-logs
    enabled: true
    paths:
      - /var/log/apps/account-service/elk.log
    json:
      keys_under_root: true
      overwrite_keys: true
      add_error_key: true
      message_key: message
    fields:
      service: account-service
    fields_under_root: false

  - type: log
    id: nodejs-transaction-logs
    enabled: true
    paths:
      - /var/log/apps/transaction-api/app-*.log
    json:
      keys_under_root: true
      overwrite_keys: true
      add_error_key: true
      message_key: message
    fields:
      service: transaction-api
    fields_under_root: false

output.logstash:
  hosts: ["logstash:5044"]
  loadbalance: true
  backoff.init: 1s
  backoff.max: 60s

filebeat.registry.flush: 1s
logging.level: info
